language: go

sudo: false

go:
  - 1.5
  - tip

install:
 - go get -u github.com/alecthomas/gometalinter
 - go get github.com/codegangsta/cli github.com/signalfx/golib/datapoint github.com/signalfx/metricproxy/protocol/signalfx github.com/gogo/protobuf/proto github.com/prometheus/client_golang/prometheus github.com/prometheus/client_model/go
 - gometalinter --install --update

script:
  - export GO15VENDOREXPERIMENT=1
  - go test -v scrapper_lib
  - go build scrapper
  - gometalinter -D structcheck -D gotype -D aligncheck .
