language: go

sudo: false

go:
  - 1.5
  - tip

install:
 - go get -u github.com/alecthomas/gometalinter
 - gometalinter --install --update

script:
  - export GO15VENDOREXPERIMENT=1
  - go test -v .
  - go build .
  - gometalinter -D structcheck -D gotype -D aligncheck .
